FileVersion = 1
Projects = {SourceBeef = {Path = "SourceBeef"}, SourceBeef-SDK = "*", SourceBeefAPI = {Path = "SourceBeefAPI"}}
Unlocked = ["SourceBeef-SDK"]

[Workspace]
StartupProject = "SourceBeef"
