FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win32"
RecentFilesList = ["c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\API.bf", "SourceBeef\\src\\SourceBeef.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\corlib\\src\\Internal.bf", "SourceBeef\\src\\ServerPlugin.bf", "SourceBeef-SDK\\src\\Core\\IPlugin.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\IVEngineServer.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\CGlobalVars.bf", "SourceBeefAPI\\src\\Exports.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\SBPluginGen.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Common\\Types.bf", "Disassembly", "Disassembly", "SourceBeefAPI\\src\\Program.bf", "Disassembly", "Disassembly", "d:\\a01\\_work\\4\\s\\src\\vctools\\crt\\vcruntime\\src\\string\\i386\\MEMCPY.ASM", "Disassembly", "Disassembly", "Disassembly", "Disassembly"]

[MainWindow]
X = 0
Y = 0
Width = 1260
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 222.0
RequestedHeight = 266.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 330.0
SizePriority = 318.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1918.0
RequestedHeight = 64.0
SizePriority = 64.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Exports.bf"
TabWidth = 89.0
Type = "SourceViewPanel"
FilePath = "SourceBeefAPI\\src\\Exports.bf"
CursorPos = 1042
VertPos = 135.0
ProjectName = "SourceBeefAPI"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CGlobalVars.bf"
TabWidth = 117.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\CGlobalVars.bf"
CursorPos = 2049
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Types.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Common\\Types.bf"
CursorPos = 123
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SBPluginGen.bf"
TabWidth = 117.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\SBPluginGen.bf"
CursorPos = 235
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "API.bf"
TabWidth = 63.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\API.bf"
CursorPos = 1525
VertPos = 540.0
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IPlugin.bf"
TabWidth = 83.0
Type = "SourceViewPanel"
FilePath = "SourceBeef-SDK\\src\\Core\\IPlugin.bf"
CursorPos = 4080

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SourceBeef.bf"
TabWidth = 110.0
Type = "SourceViewPanel"
FilePath = "SourceBeef\\src\\SourceBeef.bf"
CursorPos = 1088
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ServerPlugin.bf"
TabWidth = 117.0
Type = "SourceViewPanel"
FilePath = "SourceBeef\\src\\ServerPlugin.bf"
CursorPos = 8908
VertPos = 3299.0
ProjectName = "SourceBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 350.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 188.0
SizePriority = 0.5594369
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 182.0}, {Width = 200.0}]
Items = ["eax", "ecx", "eax", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 118.0
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 343.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 101.0
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Class View"
TabWidth = 111.0
Type = "ClassViewPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 1594.0
RequestedHeight = 188.0
SizePriority = 0.4405631
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\IPlugin.bf"
Line = 66
Column = 2

[[Breakpoints]]
File = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\IPlugin.bf"
Line = 58
Column = 3

[[Breakpoints]]
File = "SourceBeefAPI\\src\\Program.bf"
Line = 20
Column = 4

[DebuggerDisplayTypes."Source_Tools.bsp.lump_t[64].[]"]
IntDisplayType = "Binary"

[DebuggerDisplayTypes.""]
IntDisplayType = "Decimal"
