FileVersion = 1
Dependencies = {corlib = "*", SourceBeef-SDK = "*"}

[Project]
Name = "SourceBeefAPI"
TargetType = "BeefLib"
StartupObject = "SourceBeefAPI.Program"

[Configs.Debug.Win32]
BuildKind = "DynamicLib"

[Configs.Release.Win32]
BuildKind = "DynamicLib"
