FileVersion = 1
LastConfig = "Debug_CStrike"
LastPlatform = "Win32"
RecentFilesList = ["c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Common\\Types.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\CGlobalVars.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSGO\\CGlobalVars.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\corlib\\src\\Collections\\Dictionary.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Common\\Util.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\API.bf", "c:\\Users\\Herman\\Projects\\SourceBeef3\\SamplePlugin\\src\\MyPlugin.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\IPlugin.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "Disassembly", "c:\\Users\\Herman\\Projects\\SourceBeef3\\SourceBeef\\src\\ServerPlugin.bf", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\IVEngineServer.bf", "Disassembly", "Disassembly", "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\corlib\\src\\Array.bf"]

[MainWindow]
X = -5
Y = 2
Width = 1260
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 222.0
RequestedHeight = 266.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 330.0
SizePriority = 318.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1918.0
RequestedHeight = 64.0
SizePriority = 64.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Types.bf"
TabWidth = 89.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Common\\Types.bf"
CursorPos = 118
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CGlobalVars.bf"
TabWidth = 127.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSGO\\CGlobalVars.bf"
CursorPos = 20
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CGlobalVars.bf"
TabWidth = 127.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\CGlobalVars.bf"
CursorPos = 21
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Dictionary.bf"
TabWidth = 113.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\corlib\\src\\Collections\\Dictionary.bf"
CursorPos = 7211
VertPos = 4440.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Util.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Common\\Util.bf"
CursorPos = 253
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IVEngineServer.bf"
TabWidth = 131.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\CSS\\IVEngineServer.bf"
CursorPos = 2824
VertPos = 1004.0
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ServerPlugin.bf"
TabWidth = 117.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\Projects\\SourceBeef3\\SourceBeef\\src\\ServerPlugin.bf"
CursorPos = 10021
VertPos = 4020.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 66154
VertPos = 43305.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "IPlugin.bf"
TabWidth = 83.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\IPlugin.bf"
CursorPos = 459
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "API.bf"
TabWidth = 63.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\AppData\\Local\\BeefLang\\BeefLibs\\SourceBeef-SDK\\src\\Core\\API.bf"
CursorPos = 1726
VertPos = 585.0
ProjectName = "SourceBeef-SDK"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MyPlugin.bf"
TabWidth = 98.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Herman\\Projects\\SourceBeef3\\SamplePlugin\\src\\MyPlugin.bf"
CursorPos = 488
VertPos = 45.0
ProjectName = "SamplePlugin"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 350.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 188.0
SizePriority = 0.5594369
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 329.0}, {Width = 200.0}]
Items = ["TIER0_LIB", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Breakpoints"
TabWidth = 118.0
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 343.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 101.0
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Class View"
TabWidth = 111.0
Type = "ClassViewPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 1594.0
RequestedHeight = 188.0
SizePriority = 0.4405631
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[DebuggerDisplayTypes."Source_Tools.bsp.lump_t[64].[]"]
IntDisplayType = "Binary"

[DebuggerDisplayTypes.""]
IntDisplayType = "Decimal"
