FileVersion = 1
Dependencies = {corlib = "*", SourceBeef-SDK = "*"}

[Project]
Name = "SourceBeef"
TargetType = "BeefLib"
StartupObject = "SourceBeef.SourceBeef"

[Configs.Debug.Win32]
BuildKind = "DynamicLib"

[Configs."Debug - CStrike".Win32]
BuildKind = "DynamicLib"
BeefLibType = "Static"

[Configs.Release.Win32]
BuildKind = "DynamicLib"
